/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareDiaryRouteImport } from './routes/share-diary'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RecordRouteImport } from './routes/record'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as MyRouteImport } from './routes/my'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as FortuneRouteImport } from './routes/fortune'
import { Route as ExchangeDiaryRoomRouteImport } from './routes/exchange-diary-room'
import { Route as ExchangeDiaryJoinRouteImport } from './routes/exchange-diary-join'
import { Route as ExchangeDiaryCreateRouteImport } from './routes/exchange-diary-create'
import { Route as ExchangeDiaryRouteImport } from './routes/exchange-diary'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdviceRouteImport } from './routes/advice'
import { Route as IndexRouteImport } from './routes/index'

const ShareDiaryRoute = ShareDiaryRouteImport.update({
  id: '/share-diary',
  path: '/share-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const FortuneRoute = FortuneRouteImport.update({
  id: '/fortune',
  path: '/fortune',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeDiaryRoomRoute = ExchangeDiaryRoomRouteImport.update({
  id: '/exchange-diary-room',
  path: '/exchange-diary-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeDiaryJoinRoute = ExchangeDiaryJoinRouteImport.update({
  id: '/exchange-diary-join',
  path: '/exchange-diary-join',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeDiaryCreateRoute = ExchangeDiaryCreateRouteImport.update({
  id: '/exchange-diary-create',
  path: '/exchange-diary-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeDiaryRoute = ExchangeDiaryRouteImport.update({
  id: '/exchange-diary',
  path: '/exchange-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/exchange-diary': typeof ExchangeDiaryRoute
  '/exchange-diary-create': typeof ExchangeDiaryCreateRoute
  '/exchange-diary-join': typeof ExchangeDiaryJoinRoute
  '/exchange-diary-room': typeof ExchangeDiaryRoomRoute
  '/fortune': typeof FortuneRoute
  '/intro': typeof IntroRoute
  '/my': typeof MyRoute
  '/presentation': typeof PresentationRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/share-diary': typeof ShareDiaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/exchange-diary': typeof ExchangeDiaryRoute
  '/exchange-diary-create': typeof ExchangeDiaryCreateRoute
  '/exchange-diary-join': typeof ExchangeDiaryJoinRoute
  '/exchange-diary-room': typeof ExchangeDiaryRoomRoute
  '/fortune': typeof FortuneRoute
  '/intro': typeof IntroRoute
  '/my': typeof MyRoute
  '/presentation': typeof PresentationRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/share-diary': typeof ShareDiaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/exchange-diary': typeof ExchangeDiaryRoute
  '/exchange-diary-create': typeof ExchangeDiaryCreateRoute
  '/exchange-diary-join': typeof ExchangeDiaryJoinRoute
  '/exchange-diary-room': typeof ExchangeDiaryRoomRoute
  '/fortune': typeof FortuneRoute
  '/intro': typeof IntroRoute
  '/my': typeof MyRoute
  '/presentation': typeof PresentationRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/share-diary': typeof ShareDiaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advice'
    | '/analysis'
    | '/chat'
    | '/exchange-diary'
    | '/exchange-diary-create'
    | '/exchange-diary-join'
    | '/exchange-diary-room'
    | '/fortune'
    | '/intro'
    | '/my'
    | '/presentation'
    | '/record'
    | '/report'
    | '/share-diary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advice'
    | '/analysis'
    | '/chat'
    | '/exchange-diary'
    | '/exchange-diary-create'
    | '/exchange-diary-join'
    | '/exchange-diary-room'
    | '/fortune'
    | '/intro'
    | '/my'
    | '/presentation'
    | '/record'
    | '/report'
    | '/share-diary'
  id:
    | '__root__'
    | '/'
    | '/advice'
    | '/analysis'
    | '/chat'
    | '/exchange-diary'
    | '/exchange-diary-create'
    | '/exchange-diary-join'
    | '/exchange-diary-room'
    | '/fortune'
    | '/intro'
    | '/my'
    | '/presentation'
    | '/record'
    | '/report'
    | '/share-diary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdviceRoute: typeof AdviceRoute
  AnalysisRoute: typeof AnalysisRoute
  ChatRoute: typeof ChatRoute
  ExchangeDiaryRoute: typeof ExchangeDiaryRoute
  ExchangeDiaryCreateRoute: typeof ExchangeDiaryCreateRoute
  ExchangeDiaryJoinRoute: typeof ExchangeDiaryJoinRoute
  ExchangeDiaryRoomRoute: typeof ExchangeDiaryRoomRoute
  FortuneRoute: typeof FortuneRoute
  IntroRoute: typeof IntroRoute
  MyRoute: typeof MyRoute
  PresentationRoute: typeof PresentationRoute
  RecordRoute: typeof RecordRoute
  ReportRoute: typeof ReportRoute
  ShareDiaryRoute: typeof ShareDiaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-diary': {
      id: '/share-diary'
      path: '/share-diary'
      fullPath: '/share-diary'
      preLoaderRoute: typeof ShareDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortune': {
      id: '/fortune'
      path: '/fortune'
      fullPath: '/fortune'
      preLoaderRoute: typeof FortuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-diary-room': {
      id: '/exchange-diary-room'
      path: '/exchange-diary-room'
      fullPath: '/exchange-diary-room'
      preLoaderRoute: typeof ExchangeDiaryRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-diary-join': {
      id: '/exchange-diary-join'
      path: '/exchange-diary-join'
      fullPath: '/exchange-diary-join'
      preLoaderRoute: typeof ExchangeDiaryJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-diary-create': {
      id: '/exchange-diary-create'
      path: '/exchange-diary-create'
      fullPath: '/exchange-diary-create'
      preLoaderRoute: typeof ExchangeDiaryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-diary': {
      id: '/exchange-diary'
      path: '/exchange-diary'
      fullPath: '/exchange-diary'
      preLoaderRoute: typeof ExchangeDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdviceRoute: AdviceRoute,
  AnalysisRoute: AnalysisRoute,
  ChatRoute: ChatRoute,
  ExchangeDiaryRoute: ExchangeDiaryRoute,
  ExchangeDiaryCreateRoute: ExchangeDiaryCreateRoute,
  ExchangeDiaryJoinRoute: ExchangeDiaryJoinRoute,
  ExchangeDiaryRoomRoute: ExchangeDiaryRoomRoute,
  FortuneRoute: FortuneRoute,
  IntroRoute: IntroRoute,
  MyRoute: MyRoute,
  PresentationRoute: PresentationRoute,
  RecordRoute: RecordRoute,
  ReportRoute: ReportRoute,
  ShareDiaryRoute: ShareDiaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
